// Generates src/frames/nut00b-data.ts from ERFA's `nut00b.c` (IAU 2000B luni-solar nutation series).
//
//   node packages/physics/scripts/generate-nut00b.mjs
//
// The table is factual scientific data (McCarthy & Luzum 2003; IERS Conventions 2003/2010) as
// published in the IAU SOFA and ERFA libraries. ERFA is distributed under the BSD-3-Clause
// licence: https://github.com/liberfa/erfa/blob/master/LICENSE — see /NOTICE.
//
// Re-running the script re-derives the file byte-for-byte; a unit test asserts row count and a
// checksum of the coefficients so accidental edits are caught.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const URL_SRC = 'https://raw.githubusercontent.com/liberfa/erfa/master/src/nut00b.c';
const res = await fetch(URL_SRC);
if (!res.ok) throw new Error(`fetch ${URL_SRC}: ${res.status}`);
const src = await res.text();

const rows = [];
for (const m of src.matchAll(
  /\{\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*([-\d.]+),\s*([-\d.]+),\s*([-\d.]+),\s*([-\d.]+),\s*([-\d.]+),\s*([-\d.]+)\s*\}/g,
)) {
  rows.push(m.slice(1, 12).map(Number));
}
if (rows.length !== 77) throw new Error(`expected 77 rows, parsed ${rows.length}`);

const fmt = (r) => `  [${r.map((v) => (Number.isInteger(v) ? String(v) : v)).join(', ')}],`;
const out = `// GENERATED by packages/physics/scripts/generate-nut00b.mjs — do not edit by hand.
// Source: ERFA nut00b.c (BSD-3-Clause), IAU 2000B nutation series, 77 luni-solar terms.
// Columns: nl, nl', nF, nD, nΩ (integer multipliers of l, l', F, D, Ω),
//          ps, pst, pc  (Δψ: sin, t·sin, cos coefficients),
//          ec, ect, es  (Δε: cos, t·cos, sin coefficients).
// Coefficient unit: 0.1 microarcsecond (and 0.1 µas per Julian century for the t· columns).

export type Nut00bRow = readonly [
  nl: number,
  nlp: number,
  nf: number,
  nd: number,
  nom: number,
  ps: number,
  pst: number,
  pc: number,
  ec: number,
  ect: number,
  es: number,
];

export const NUT00B_TERMS: readonly Nut00bRow[] = [
${rows.map(fmt).join('\n')}
];
`;
const dest = fileURLToPath(new URL('../src/frames/nut00b-data.ts', import.meta.url));
writeFileSync(dest, out);
console.log(`wrote ${rows.length} rows to ${dest}`);
