package sim;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.hipparchus.geometry.euclidean.threed.Vector3D;
import org.orekit.bodies.GeodeticPoint;
import org.orekit.bodies.OneAxisEllipsoid;
import org.orekit.data.DataContext;
import org.orekit.data.DirectoryCrawler;
import org.orekit.frames.EOPHistory;
import org.orekit.frames.Frame;
import org.orekit.frames.FramesFactory;
import org.orekit.frames.Transform;
import org.orekit.propagation.analytical.tle.TLE;
import org.orekit.propagation.analytical.tle.TLEPropagator;
import org.orekit.time.AbsoluteDate;
import org.orekit.time.TimeScale;
import org.orekit.time.TimeScalesFactory;
import org.orekit.utils.Constants;
import org.orekit.utils.IERSConventions;
import org.orekit.utils.PVCoordinates;

/**
 * Reference generator for Simulation's cross-implementation validation.
 *
 * For each TLE in the input file and each offset from the element epoch it writes, in SI units:
 *   - the SGP4 state in TEME (Orekit's TLEPropagator),
 *   - the same state transformed to ITRF and GCRF (IERS 2010 conventions, Orekit frames),
 *   - the Earth Orientation Parameters Orekit used at that instant (UT1-UTC, xp, yp, LOD),
 *     so the comparison can feed exactly these values into Simulation and isolate algorithm differences.
 * It also writes WGS 84 geodetic <-> ECEF conversions for a fixed set of points.
 *
 * Usage: OrekitReference <orekit-data dir> <tles.txt> <output.csv>
 */
public final class OrekitReference {

    private static final double[] OFFSETS_HOURS = {0, 1, 6, 12, 24, 48};

    public static void main(String[] args) throws IOException {
        if (args.length != 3) {
            System.err.println("usage: OrekitReference <orekit-data dir> <tles.txt> <output.csv>");
            System.exit(2);
        }
        DataContext.getDefault().getDataProvidersManager().addProvider(new DirectoryCrawler(new File(args[0])));

        TimeScale utc = TimeScalesFactory.getUTC();
        Frame teme = FramesFactory.getTEME();
        Frame itrf = FramesFactory.getITRF(IERSConventions.IERS_2010, true); // simpleEOP: no sub-daily tides
        Frame gcrf = FramesFactory.getGCRF();
        EOPHistory eop = FramesFactory.getEOPHistory(IERSConventions.IERS_2010, true);

        List<String> lines = Files.readAllLines(Path.of(args[1]), StandardCharsets.UTF_8);
        try (PrintWriter out = new PrintWriter(args[2], StandardCharsets.UTF_8)) {
            out.println("# Generated by validation/orekit (Orekit " + orekitVersion() + "). SI units: m, m/s, rad, s.");
            out.println("# kind=state: case,timeUtc,frame,x,y,z,vx,vy,vz ; kind=eop: case,timeUtc,dut1S,xpRad,ypRad,lodS");
            out.println("# kind=geo: name,latInRad,lonInRad,heightInM,x,y,z (ITRF, from the input triple),latBackRad,lonBackRad,heightBackM (Orekit inverse)");
            for (int i = 0; i + 2 < lines.size(); i += 3) {
                String name = lines.get(i).trim();
                TLE tle = new TLE(lines.get(i + 1).trim(), lines.get(i + 2).trim());
                TLEPropagator prop = TLEPropagator.selectExtrapolator(tle);
                for (double h : OFFSETS_HOURS) {
                    AbsoluteDate date = tle.getDate().shiftedBy(h * 3600.0);
                    String iso = date.toString(utc);
                    PVCoordinates pvTeme = prop.getPVCoordinates(date, teme);
                    PVCoordinates pvItrf = teme.getTransformTo(itrf, date).transformPVCoordinates(pvTeme);
                    PVCoordinates pvGcrf = teme.getTransformTo(gcrf, date).transformPVCoordinates(pvTeme);
                    row(out, "state", name, iso, "TEME", pvTeme);
                    row(out, "state", name, iso, "ITRF", pvItrf);
                    row(out, "state", name, iso, "GCRF", pvGcrf);
                    out.println(String.format(Locale.ROOT, "eop,%s,%s,%.15e,%.15e,%.15e,%.15e",
                            name, iso,
                            eop.getUT1MinusUTC(date),
                            eop.getPoleCorrection(date).getXp(),
                            eop.getPoleCorrection(date).getYp(),
                            eop.getLOD(date)));
                }
            }

            OneAxisEllipsoid earth = new OneAxisEllipsoid(
                    Constants.WGS84_EARTH_EQUATORIAL_RADIUS, Constants.WGS84_EARTH_FLATTENING, itrf);
            AbsoluteDate any = new AbsoluteDate(2026, 9, 30, 12, 0, 0.0, utc);
            double[][] sites = {
                {0, 0, 0}, {45, 10, 0}, {-33.9, 151.2, 58}, {89.9, 45, 1000}, {-89.99, -120, 0},
                {35.4267, -116.89, 900}, {10, 170, 400_000}, {-50, -60, 35_786_000}, {23.4, 5, -400},
            };
            for (double[] s : sites) {
                GeodeticPoint gp = new GeodeticPoint(Math.toRadians(s[0]), Math.toRadians(s[1]), s[2]);
                Vector3D p = earth.transform(gp);
                GeodeticPoint back = earth.transform(p, itrf, any);
                out.println(String.format(Locale.ROOT, "geo,site(%.4f;%.4f;%.1f),%.15e,%.15e,%.15e,%.15e,%.15e,%.15e,%.15e,%.15e,%.15e",
                        s[0], s[1], s[2], gp.getLatitude(), gp.getLongitude(), gp.getAltitude(),
                        p.getX(), p.getY(), p.getZ(),
                        back.getLatitude(), back.getLongitude(), back.getAltitude()));
            }
        }
    }

    private static void row(PrintWriter out, String kind, String name, String iso, String frame, PVCoordinates pv) {
        Vector3D p = pv.getPosition();
        Vector3D v = pv.getVelocity();
        out.println(String.format(Locale.ROOT, "%s,%s,%s,%s,%.15e,%.15e,%.15e,%.15e,%.15e,%.15e",
                kind, name, iso, frame, p.getX(), p.getY(), p.getZ(), v.getX(), v.getY(), v.getZ()));
    }

    private static String orekitVersion() {
        Package p = TLE.class.getPackage();
        String v = p == null ? null : p.getImplementationVersion();
        return v == null ? "13.x" : v;
    }
}
